// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: proto/auth.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'auth';

export interface AuthenticateRequest {
  token: string;
}

export interface ValidateUserRequest {
  userId: string;
  /** e.g., ELDER, CAREGIVER */
  role: string;
}

export interface ValidateUserResponse {
  isValid: boolean;
  user: User | undefined;
}

export interface GetUsersByIdsRequest {
  userIds: string[];
}

export interface GetUsersByIdsResponse {
  users: User[];
}

/** Lightweight user shape for authentication only */
export interface AuthUser {
  id: string;
  email: string;
  role: string;
}

/** Full user shape for profile/validation flows */
export interface User {
  id: string;
  email: string;
  role: string;
  firstName: string;
  lastName: string;
  mobileNumber: string;
  avatar: string;
}

export const AUTH_PACKAGE_NAME = 'auth';

export interface AuthServiceClient {
  authenticate(request: AuthenticateRequest): Observable<AuthUser>;
}

export interface AuthServiceController {
  authenticate(
    request: AuthenticateRequest
  ): Promise<AuthUser> | Observable<AuthUser> | AuthUser;
}

export function AuthServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ['authenticate'];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method
      );
      GrpcMethod('AuthService', method)(
        constructor.prototype[method],
        method,
        descriptor
      );
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method
      );
      GrpcStreamMethod('AuthService', method)(
        constructor.prototype[method],
        method,
        descriptor
      );
    }
  };
}

export const AUTH_SERVICE_NAME = 'AuthService';

export interface UserServiceClient {
  validateUser(request: ValidateUserRequest): Observable<ValidateUserResponse>;

  getUsersByIds(
    request: GetUsersByIdsRequest
  ): Observable<GetUsersByIdsResponse>;
}

export interface UserServiceController {
  validateUser(
    request: ValidateUserRequest
  ):
    | Promise<ValidateUserResponse>
    | Observable<ValidateUserResponse>
    | ValidateUserResponse;

  getUsersByIds(
    request: GetUsersByIdsRequest
  ):
    | Promise<GetUsersByIdsResponse>
    | Observable<GetUsersByIdsResponse>
    | GetUsersByIdsResponse;
}

export function UserServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ['validateUser', 'getUsersByIds'];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method
      );
      GrpcMethod('UserService', method)(
        constructor.prototype[method],
        method,
        descriptor
      );
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method
      );
      GrpcStreamMethod('UserService', method)(
        constructor.prototype[method],
        method,
        descriptor
      );
    }
  };
}

export const USER_SERVICE_NAME = 'UserService';
