version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: elder_auth_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${AUTH_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AUTH_POSTGRES_PASSWORD}
      POSTGRES_DB: ${AUTH_POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend-net

  adminer:
    image: adminer
    container_name: ec_adminer
    restart: always
    ports:
      - '${ADMINER_PORT}:8080'
    networks:
      - backend-net

volumes:
  pgdata:

networks:
  backend-net:
    driver: bridge
