name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma client
        run: npx nx run elder-auth:prisma:generate

      - name: Lint
        run: npx nx run-many -t lint --parallel=3 || true

      - name: Build elder-auth
        run: npx nx build elder-auth

      - name: Run unit tests
        run: npx nx run-many -t test --parallel=3 --code-coverage

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: elder-auth-dist
          path: dist/apps/elder-auth
          if-no-files-found: warn
